[package]
name = "quart_lib"
version = "0.1.0"
authors = ["Anton Hermann <antonoehler@gmx.de>"]
edition = "2018"

[features]
default = ["termion"]

[dependencies]
termion = { version = "1.5.4", optional = true }
log = "0.4.8"
flexi_logger = "0.14.8"
match_cfg = "0.1.0"
